const product=9*9;
const quotient=56/12;
const remainder=281%9;
const divByZero=18/0;
const stringSum="56" +"92";
const bool= 42>52;
console.log(product);
console.log(quotient);
console.log(remainder);
console.log(divByZero);
console.log(stringSum);
console.log(bool);
